// Generated by Selenium IDE

import io.github.bonigarcia.wdm.ChromeDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.JavascriptExecutor;
import project.ui.pages.LoginPage;

import java.util.*;

public class DefaultSuiteTesAmazon {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
//        ChromeDriverManager.getInstance().version("76.0.3809.126").setup();
//        ChromeOptions chromeOptions = new ChromeOptions();
//        chromeOptions.addArguments("--incognito");
//        driver = new ChromeDriver(chromeOptions);
    }

    @After
    public void tearDown() {
     //   driver.quit();
    }

    @Test
    public void login() {
//    driver.get("https://www.amazon.com//");
//    driver.findElement(By.cssSelector("#nav-link-accountList > .nav-line-2")).click();
//    driver.findElement(By.id("ap_email")).sendKeys("johnpiterzon@gmail.com");
//    driver.findElement(By.cssSelector(".a-button-inner > #continue")).click();
//    driver.findElement(By.id("ap_password")).sendKeys("Holamundo@1");
//    driver.findElement(By.id("signInSubmit")).click();
        LoginPage loginPage = new LoginPage();
        loginPage.login();
        assertEquals(loginPage.message(),"Authentication required");
    }
}
